1EdTech/openbadges-specification

- examples/index.md
- extensions/index.md
- index.md
- stylesheets/styles.css
Thanks to @threeqube for adding all the necessary anchor links for the JSON-LD context. Now I've done a quick rework of the organization of this document, and added a little bit of content here and there. Mainly, moved examples onto the examples page and linked back and forth between them and the definitions they depend on.
See http://ottonomy.github.io/openbadges-specification/ for how it looks if we pull this in.
> reorganized sections, refactored examples into examples/index.md

- CNAME
Once a CNAME is set up on the DNS record, this pull request can be merged to update the GH Pages settings to properly map the http://standard.openbadges.org domain to this site.
> Add CNAME record to allow domain mapping for GH-pages

- Assertion/latest.md
According to the [validator](https://github.com/mozilla/openbadges-validator/blob/master/index.js#L117), `hashed` is required.  Not optional.
> Changed validity rules for `hashed` to be required

- index.md
Following up on feedback that to make 1.1 badges valid JSON-LD in all their properties, additional properties outside the OBI vocabulary should be mapped to IRIs in the context.
> verbiage declaring IRI mapping as required for additional properties

- history/1.1.md
Thanks, @erickorb and @msporny for reporting that the 1.1 history/changelog page incorrectly advised implementers to use insecure `http` for the context URL instead of `https`. Indeed HTTPS should be used.
> Update 1.1 examples to https

- v0/context.json
- v1/context.json
Badge products will need to translate dateTime stamps into xsd:dateTime / ISO 8601 before doing Linked Data processing, or they may encounter slight compaction errors yielding incorrect compact IRIs.
See http://docstore.mik.ua/orelly/xml/schema/ch04_05.htm for documentation.
> Reestablish xsd:dateTime format for issuedOn and expires

- .gitignore
- extensions/index.md
- stylesheets/styles.scss
Extensions published on the openbadgespec extensions page should have authorship information available so folks who have questions or want to express praise have a point of contact.
> Add extension authorship and remote hosting info

- index.md
I'm proposing a change to better account for non-organizational (i.e. individual) issuer entities.
I propose that we change the name of the `IssuerOrganization` data class to `Issuer Profile`. The linked data IRI https://w3id.org/openbadges/#Issuer should stay the same. Corrects one error in documentation between docs and core context file.
Benefits:
* More explicitly support the fact that individual people may be issuers of Open Badges
Drawbacks: 
* None known.
Any objections to merging or questions?
> Updates IssuerOrg to Issuer Profile

- v1/schema/badgeclass.json
In the current version of the BadgeClass schema, the TagsArray definition has a property called "uniqueness" to denote that the values in that array should be unique. However, this is not a supported property in the [JSON Schema specification](http://json-schema.org/draft-04/schema#).
```json
{
"$schema": "http://json-schema.org/draft-04/schema#",
"properties": {
"uniqueItems": {
"type": "boolean",
"default": false
}
}
}
```
> Changed uniqueness property to uniqueItems

- v2/context.json
When I try to reference the v2 context, I get the following error (through JSON-LD playground). I think it's just the trailing comma
```
Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.
```
> remove trailing comma

- stylesheets/styles.scss
On my system (Ubuntu 16.10, Chrome), code displays with a non-monospace font, which makes it really hard to read. This is because all fonts that are used in the stylesheet for code are neither installed on my system nor imported by the document. As a quick fix, this PR adds a fallback to `monospace`, which should be available everywhere.
> Fallback to monospace font for code

- index.md
This fixes #116 by inserting CRs before two div.tablewrapper open tags.
> Fix table markdown rendering in Endorsement section

- index.md
Embarrassingly, "Specification" was misspelled in the specification. This one-line fix corrects that error.
> Fix spelling error/typo of 'Specification'

- index.md
The ambiguous term "assertion" has been augmented to read "assertion of endorsement" in two locations describing the new Endorsement class. This improves understanding of the similarity between Endorsements and Assertions and common usage of their shared properties.
Fixes #108.
> Improve clarity of Endorsement verification instructions per #108

- index.md
The document declares the `verification` property in scope for the `Profile` class, but it was accidentally omitted from the table describing Profile. This PR corrects that omission.
> Add verification as property in scope for issuer Profile

- index.md
Resolves #120. Usage of an incorrect property, though valid JSON-LD in the v2 context, made the Simple Example at the top of the spec an invalid Assertion. `issuedOn` is required. `created` is a similar term from a different vocabulary used for signature creation dates.
> Fix usage of incorrect property in 'A Simple Example'. Resolves #120.

- baking/index.md
Small updates to baking spec, particularly the SVG example code now using 2.0 syntax. Note: this PR goes to master and could/should therefore be included in the in-place edit updates on openbadgespec.org. Further changes to this doc will happen on the ims2.0 branch (adding IMS frontmatter etc) later on. @ottonomy, thankful if you could review.
> Updates to baking spec (#110)

- index.md
Per Issue 105# and the WGs decision on last weeks call, remove the bullet on in development multilingual badges. The examples section linked to already advises against using this technique (and instead recommends the technique in the bullet above), so AFAICS no further changes are needed.
> Remove "In development bullet" for multilingual badges (#105)

- index.md
Clarifies working draft licensing per IMS requirements.
Replaces PR #134 which was based on the wrong branch.
> Update license for IMS Working Draft

- README.md
Updated mentions of Badge Alliance to refer to IMS Global
> Changed references of Badge Alliance to IMS Global

- index.md
* Change the definition of array as proposed in #167
* Add "Multiple values allowed" with link to array definition to the
following fields:
-Assertion: evidence
-BadgeClass: alignment, tags
-VerificationObject: allowedOrigins
-RevocationList: revokedAssertions
-Several classes: related
-Extension: validation
-All instances of @type
* The description fields for the values above now describe the data
type using singularis in an attempt to be clear that the restriction
applies to each individual entry in the array.
> changes to definition of Array and fields with multiple values (167)

- extensions/exampleExtension/context.json
- extensions/geoCoordinatesExtension/context.json
- extensions/geoCoordinatesExtension/schema.json
- extensions/index.md
The Extensions Cleanup Posse is in full (unofficial) swing. (Merge PR #173 first for a clean diff here, as this includes that commit)
Fixes an error with the GeoLocationExtension JSON-schema, where the "required" declaration was in an invalid location in the file, so it wasn't a valid schema. Now it will be possible to publish a valid instance of the extension.
> Geolocation extension fix

- extensions/index.md
Added empty line between horizontal rule and Community Extensions heading. Prior line of text was rendered incorrectly as h2.
> extensions/index.md Removed typo to fix heading size issue

- impl/index.md
Added statement about use of urn-based vs. http-based BadgeClass identifiers. Resolves issue #204
> Recommendation for preventing BadgeClass deletions

- ob_v2p1/ob-spec-v2p1.html
PR fixes #241, #242, and #245
- Modified GET /assertions response envelope to contain two result arrays: "assertions", and "signedBadges".
- All other responses remain unchanged.
Note: Now that the responses to GET /assertions, GET /profile, and POST /profile have different shapes, do you want to change the results property for GET /profile and POST /profile to a singular "profile" property? For example,
```
{
"status": {STATUS...},
"profile": {PROFILE...}
}
```
> Modify request payloads and response envelopes to separate signed and unsigned assertions

- ob_v2p0/extensions/assessmentExtension/index.html
- ob_v2p0/extensions/extraDescription/index.html
- ob_v2p0/extensions/index.md
- ob_v2p0/extensions/issuerAccreditationExtension/index.html
This update includes:
- Setting status of Assessment, IssuerAccreditation, and ExtraDescription extensions to Candidate Final Public
- Setting all URLs for IMS purl server to https
- Fixing a broken link to ExtraDescription files
> Set extensions as public; update typos

- ob_v2p0/history/2.0.md
- ob_v2p0/v2/context.json
In October 2020, the work group indicated that an error with the `targetFramework` term in the [V2 Context](https://w3id.org/openbadges/v2) should be corrected in place. This term previously referenced a non-existent `schema:targetFramework` term when the appropriate term in schema.org's vocabulary is [educationalFramework](http://schema.org/educationalFramework). An impact analysis was performed resulting in a conclusion that there would be very little effect on implementations in any role.
Resolves #272
> Correct schema:targetFramework reference to schema:educationalFramework

- ob_v2p0/index.md
Addresses #254 
Removes the reference to email-only support in platforms and adjusts the reference to current popularity.
> Update reference to email prevalence

- ob_v2p0/examples/index.md
- ob_v2p0/history/2.0.md
- ob_v2p0/index.md
Addresses issue #218 and adds the `issuedOn` field to all Endorsement examples
> Endorsement errata

- ob_v2p0/history/2.0.md
- ob_v2p0/index.md
Implementers need to know that an exact match of a specific format of the IRI is required to pass current validation for the property `validatesType` as it is used in extensions.
Resolves #180
> Clarify the requirements for validatesType

- ob_v2p0/examples/index.md
- ob_v2p0/history/2.0.md
- ob_v2p0/index.md
This was a bit more involved than I had previously thought. The `revocationList` has a `revokedAssertions` property that implies only Assertions may be revoked (even though Endorsements are basically Assertions, too).
I think we can navigate any confusion on this matter, but it did have me thinking about a possible rename of `revokedAssertions` to `revocations` or even splitting them across properties. Perhaps for a new version of the spec?
> Adds endorsement class information regarding revocation #208

- ob_v2p0/examples/index.md
- ob_v2p0/extensions/endorsement/index.md
- ob_v2p0/faq/index.md
- ob_v2p0/history/2.0.md
- ob_v2p0/index.md
- ob_v2p0/v2/context.json
Includes all errata changes since October 2020
> Update ob_v2p0 from develop

- ob_v2p1/ob-spec-v2p1.html
Fixes #307
Because the problem is that something is missing, it is hard to be confident that I found all occurrences. Please let me know if the substring "ims/ob/v2p1" should be added anywhere else.
Note: This preview ONLY includes the changes in this PR:
[Open Badges Specification 2.1 IMS Candidate Final Public.pdf](https://github.com/IMSGlobal/openbadges-specification/files/7401544/Open.Badges.Specification.2.1.IMS.Candidate.Final.Public.pdf)
> Fix missing substring on endpoint labelling

- ob_v3p0/bestpractices.md
- ob_v3p0/datamodel.html
- ob_v3p0/integrity.md
- ob_v3p0/introduction.md
- ob_v3p0/ob_v3p0.lines
This PR creates the "Proofs" section.
- Restrict VC-JWT options in [Section 6.3.1 JSON Web Token](https://www.w3.org/TR/vc-data-model/#json-web-token) to conform with IMS Security Framework 1.1 key requirements
- Clarify how presentations are using VC-JWT
- Add proof related data models
> Create Proofs section

- ob_v3p0/context.json
Discussed in CLR project group on 3/31:
- OpenBadgeCredential in the "obi" namespace
- AchievementCredential is an alias for OpenBadgeCredential
```
"OpenBadgeCredential": "obi:OpenBadgeCredential",
"AchievementCredential": "OpenBadgeCredential",
```
Closes #381 and [CLR #269](https://github.com/IMSGlobal/ComprehensiveLearnerRecord/issues/269)
> Define OpenBadgeCredential and AchievementCredential

- ob_v3p0/api.html
- ob_v3p0/datamodel.html
- ob_v3p0/integrity.md
- ob_v3p0/ob_v3p0.html
- ob_v3p0/respec-support/local-biblio.js
- ob_v3p0/vc-extensions.html
- ob_v3p0/verification.md
- Rewrite Verifiable Credentials Extensions section to include normative references to VC-EXTENSION-REGISTRY and LDS-ED25519-2020. This allows a normative requirement for Linked Data Proof with Ed25519 Signature.
- Add Linked Data Proof with Ed25519 Signature to Proofs (Signature)
- Move verification process to new Verification section which references both VC-JWT and embedded proofs
- Misc data model and biblio additions
Copy any changes to CLR 2.0 so proof methods and verification process stay in sync
Resolves #365 and #331
> Add Linked Data Proof with Ed25519 Signature

- ob_v2p1/ob-spec-v2p1.html
The example manifest had the field `"version": "v1p0"`. This corrects the example string to the final adopted version identifier for this specification `v2p1` and updates the text descriptive of this field.
> Errata: update example and description of 'version' field in manifest for v2p1

- ob_v3p0/bestpractices.md
Reference to issuers in the Presentation term was missing the closing bracket, leading to not displaying the link correctly
> Added missing `]`

- README.md
As discussed in 10.20.2022 workgroup meeting:
This PR adds a description to labels (related to the specification lifecycle) to the README.
I also recommend adding a description to the labels themselves within Github.
> Documentation: Update README with contributing guidelines for issue labels

- ob_v3p0/common_credentials.lines
Add `name` and `description` fields to EndorsementCredential to match AchievementCredential and ClrCredential. These are optional fields that can make summary displays (such as in wallets) easier.
I forgot to add them to EndorsementCredential.
> Add display fields to EndorsementCredential

- ob_v3p0/common_credentials.lines
- ob_v3p0/impl/recommended-practices.md
Resolves #537, showing how an issuer might wish to add an email address or name to a credential for extra authenticability
> Adds examples for extra subject identifiers

- ob_v3p0/impl/recommended-practices.md
This pull request adds three sections about alignment of achievements with non-1EdTech vocabularies, such Credential Engine.
The new sections are right below the section about alignment with CASE.
The content of the sections is what was showcases and approved at the meeting on Nov 9th. See the agenda document for more information.
> Implementation Guide: Added sections about alignment with Credential Engine

- ob_v3p0/common_credentials.lines
- ob_v3p0/context-3.0.3.json
- ob_v3p0/impl/migrating.md
Proposal to solve issue #550 using the action number 2:
> Add a new property inLanguage to the context, such as with the https://schema.org/inLanguage IRI and update relevant > classes, schema, and examples in implementation guide to use that property. This completely solves the problem with very > little "splash damage". But it doesn't take advantage of any JSON-LD special features for string labeling.
Rendered versions of the documents can be found at:
- Spec: https://github.com/1EdTech/openbadges-specification/blob/550-misuse-of-language-in-examples-and-i18n-documentation/docs/ob_v3p0.html
- Implementation Guide: https://github.com/1EdTech/openbadges-specification/blob/550-misuse-of-language-in-examples-and-i18n-documentation/docs/ob_v3p0_impl.html
I suggest to download the files and …
> 550 misuse of language in examples and i18n documentation

- ob_v3p0/common_credentials.lines
The gap between "OnHold" with its somewhat negative connotation and "Completed" is big enough to squeeze in another possibility, "Provisional". This carries the expectation of an eventual completed result, but perhaps has not passed all administrative checks that will complete the status.
See existing terms: https://www.imsglobal.org/spec/ob/v3p0#org.1edtech.ob.v3p0.resultstatustype.class
I have some use cases for this for self-claimed badges that are not yet fully confirmed by their issuer, but may be useful to circulate in any case. Consumers SHOULD view this as an incomplete status, but they MAY consider it satisfactory.
> Add Result.status Provisional

- ob_v3p0/impl/ob_impl_v3p0.html
This pull request includes a couple of changes to the `ob_v3p0/impl/ob_impl_v3p0.html` file to update the document version.
Document version updates:
* [`ob_v3p0/impl/ob_impl_v3p0.html`](diffhunk://#diff-a1e11c8e7c9fce6e23299deb9450efd0f07449a2673da5bd83e3a7535990d72bL40-R40): Updated `docVersion` from '1.2' to '2' in the specification details section.
* [`ob_v3p0/impl/ob_impl_v3p0.html`](diffhunk://#diff-a1e11c8e7c9fce6e23299deb9450efd0f07449a2673da5bd83e3a7535990d72bL272-R272): Updated the document version from '1.2' to '2' in the revision history table.
> Update document version from 1.2 to 2 in ob_impl_v3p0.html
