0.5/0.5_backpack_error.json
0.5/context.json
1.0/context.json
1.1/context.json
_includes/footer.html

fix spelling error in one JSON-LD term mapping

---

CNAME
_config.yml
examples/index.md
extensions/exampleExtension/context.json
extensions/exampleExtension/schema.json
extensions/index.md
index.md

Here's the example extension we've been waiting for. Cheers!
Next up, building a real useful extension. (This one could actually be used, but there's not really any point to it.)
@threeqube @kayaelle @cmcavoy

Adds an example of a usable format for community-developed extensions.

---

vocabulary.html

Adds draft vocabulary to repo.

add vocab to current origin gh-pages branch

---

examples/index.md

Thanks to @erickorb for reporting additional documentation inconsistencies.

Update examples to proper 1.1 code for final context version

---

extensions/endorsement/context.json
extensions/endorsement/schema.json
extensions/index.md

The endorsement extension adds the ability for third party issuers

Endorsement Extension

---

extensions/accessibilityExtension/context.json
extensions/accessibilityExtension/schema.json
extensions/index.md

A proposal to extend accessibility based on https://schema.org/CreativeWork
Vocabolary for accessibility proprieties: http://www.w3.org/wiki/WebSchemas/Accessibility

Added accessibility extension

---

extensions/applyLinkExtension/context.json

Fix #62 for gh-pages branch

---

extensions/accessibilityExtension/schema.json

Fix #61 for gh-pages branch

---

extensions/applyLinkExtension/context.json

FIx #62 for master branch

---

extensions/accessibilityExtension/schema.json

Fix #61 for master branch

---

extensions/index.md
extensions/issuerAccreditationExtension/context.json
extensions/issuerAccreditationExtension/schema.json

This is the first draft of the OBEE Issuer Accreditation Extension documentation, context, schema and examples.

First draft of Issuer Accreditation Extension

---

history/2.0.md
index.md

Add changes doc for 2.0, remove "Since 1.1" monikers

Add changes doc for 2.0, remove "Since 1.1" monikers

---

extensions/index.md

Fix context URI for cc extension, should be v2.

Fix context URI for cc extension

---

extensions/index.md

Added statement to top of page
Replaced IMS authored extensions with URL to IMS page where extensions are located

Clarify role of extensions in relation to spec & Replace IMS code w/ URL

---

index.md

Added id="implementation-verification" to Verification section under Implementation

Added element ID for Verification

---

extensions/issuerAccreditationExtension/context.json

directory was corrected to /issuerAccreditationExtension/schema.json

Fixed URL to schema.json file within context.json

---

index.md

Changed status to "Candidate Final / Public Draft", added published date of 08 March 2017, updated link to IMS forum.

Update IMS front matter

---

index.md

Complete RevocationList sentence. Fixes #144.

Complete RevocationList sentence

---

extensions/index.md

added information about the author.
Thanks

Accessibility: update author

---

extensions/index.md

Fixed very small typo

---

cert/index.md

fixed typo in URL for "Latest version"

Fixed typo in URL

---

cert/index.md

added closing quote marks to URL

Cert Guide: Fixed another typo in Latest Version URL

---

impl/index.md

added IMS canonical URL for Latest Version

Implementation Guide: Added URL for Latest Version

---

index.md

Added additional contributors and updated the copyright year to 2018

Updated list of contributors and copyright year

---

extensions/index.md

Per workgroup call, this should be under IMS extensions

Extensions: Move extraDescription to IMS extensions

---

README.md
baking/index.md
cert/index.md
examples/index.md
impl/index.md
index.md

updated list of supplier elections and modified content in a couple docs for consistency across all spec docs

Frontmatter updates

---

README.md

I'm proposing we use Git Flow for the purposes of introducing changes into this repository.

#265 Adding documentation on this repositories branching strategy.

---

ob_v2p1/ob-spec-v2p1.html

Addresses #285 failed client registration requests and that scopes requested & provided may be different

Client Registration Clarification

---

README.md
ob_v2p0/faq/index.md
ob_v2p0/history/2.0.md

Addresses copy changes related to #283

Change master to main

---

ob_v2p0/extensions/endorsement/index.md
ob_v2p0/index.md

Removes dead references to a Google document

---

ob_v2p1/schema/openapi3/imsob_v2p1.json
ob_v2p1/schema/openapi3/imsob_v2p1.yaml

Add ACG security to paths

---

ob_v2p1/schema/openapi3/imsob_v2p1.json
ob_v2p1/schema/openapi3/imsob_v2p1.yaml

Update OpenAPI 3 files with better hostname/basepath description

---

ob_v2p1/ob-spec-v2p1.html

Fixes #304 
This preview ONLY includes the changes in this PR:
[Open Badges Specification 2.1 IMS Candidate Final Public.pdf](https://github.com/IMSGlobal/openbadges-specification/files/7401527/Open.Badges.Specification.2.1.IMS.Candidate.Final.Public.pdf)

Add data types

---

ob_v2p1/ob-spec-v2p1.html

Fixes #306 
Note: This preview ONLY includes the changes in this PR:
[Open Badges Specification 2.1 IMS Candidate Final Public.pdf](https://github.com/IMSGlobal/openbadges-specification/files/7401571/Open.Badges.Specification.2.1.IMS.Candidate.Final.Public.pdf)

Add appendix Handling Null Values

---

docs/ob_v3p0.html
ob_v3p0/examples.html
ob_v3p0/vocab.html

This prototype assumes there would be one vocab file for all versions of the OB spec. In other words, the IRI for the term "obi" would remain the same for OB 3.0 as it has for OB 1.0-2.1.
There are two formats for discussion:
- Definition List - concise, but details may be overlooked
- Respec Sections - details can be called out 
Issue #329

Create prototype vocab file

---

ob_v3p0/common_credentials.lines
ob_v3p0/ob_v3p0.lines

Note: This also removes the Evidence `artifacts` property as agreed in https://github.com/IMSGlobal/ComprehensiveLearnerRecord/issues/291 (which I forgot to do).

Change plural form property names to singular form in the the shared data model (common_credentials.lines) and OB data model (ob_v3p0.lines)

---

ob_v3p0/context.json

Changed vocab.html location to new, versionless path: `/spec/vc/ob`

Versionless IRIs

---

ob_v3p0/api.html
ob_v3p0/cert/introduction.md
ob_v3p0/common_credentials.lines
ob_v3p0/context-3.0.1.json
ob_v3p0/context-3.0.2.json
ob_v3p0/docformat.md
ob_v3p0/equality-and-comparison.md
ob_v3p0/errata/errata.md
ob_v3p0/errata/ob_err_v3p0.html
ob_v3p0/examples.html
ob_v3p0/examples/achievementAlignmentCase.html
ob_v3p0/examples/achievementAlignmentCe.html
ob_v3p0/examples/basicOpenBadgeCredential.html
ob_v3p0/examples/endorsement.html
ob_v3p0/examples/fullOpenBadge.html
ob_v3p0/examples/skillAssertionCase.html
ob_v3p0/examples/skillAssertionCtdl.html
ob_v3p0/impl/getting-started.md
ob_v3p0/impl/migrating.md
ob_v3p0/impl/recommended-practices.md
ob_v3p0/introduction.md
ob_v3p0/ob_v3p0.html
ob_v3p0/readme.md
ob_v3p0/serialization.md

`@set` is for unordered collections. Since `allowedValue` is an ordered collection, a more appropriate container type is `@list`.
- https://www.w3.org/TR/json-ld11/#lists
- https://www.imsglobal.org/spec/clr/v2p0/#resultdescription

Change `allowedValue` container to `@list`

---

ob_v3p0/docformat.md
ob_v3p0/equality-and-comparison.md
ob_v3p0/ob_v3p0.html
ob_v3p0/readme.md

555 examples show issuerprofile instead of profile

---

ob_v3p0/common_credentials.lines
ob_v3p0/vocab.html
ob_v3p0/vocabulary.ttl

- `vocab.html` now contains RDFS annotations
- Added `vocab.ttl` with the ontology

551 where is the ontology

---

.github/workflows/publish_extensions_push.yml
extensions/assessmentExtension/v2p0/context.json

This pull request includes several updates and corrections to various files, focusing on adding a new extension, fixing typos, and updating document versions and dates.
* [`extensions/assessmentExtension/v2p0/context.json`](diffhunk://#diff-11fdeef5699b7fc958a92d7fb617a2a38cd7561d8a1f66717824be0f5d9ebb6fR19): Added a new extension reference for `assessmentType`.
* [`ob_v3p0/impl/getting-started.md`](diffhunk://#diff-a5a36e61f29e7ff28c56f535cd0ae97222228586e8c26d9fb830e7406e2b6cb6L352-R353): Corrected the spelling of "whether" in two instances.
* [`ob_v3p0/impl/ob_impl_v3p0.html`](diffhunk://#diff-a1e11c8e7c9fce6e23299deb9450efd0f07449a2673da5bd83e3a7535990d72bL261-R279): Corrected the spelling of "February" in the revision history section.
* …

April update
